# -*- coding: utf-8 -*-
{'name': 'CFON Invoice OCR Pro (no IAP)',
 'summary': 'OCR gratuito de facturas proveedor con plantillas por proveedor, multimoneda, líneas e impuestos. '
            'Integrado con Documentos.',
 'version': '17.0.1.1.0',
 'author': 'CFON / Custom OCR',
 'website': 'https://example.com',
 'license': 'LGPL-3',
 'category': 'Accounting/Accounting',
 'depends': ['base', 'account', 'documents'],
 'data': ['security/ir.model.access.csv',
          'views/ocr_template_views.xml',
          'views/res_config_settings_views.xml',
          'data/documents_rule.xml',
          'data/ocr_templates.xml',
          'data/ocr_templates_extra.xml',
          'data/ocr_templates_last.xml'],
 'assets': {},
 'application': False,
 'installable': True,
 'external_dependencies': {'python': ['pdfminer.six', 'python-dateutil']},
 'description': 'OCR de facturas (gratis) con plantillas por proveedor y reglas avanzadas.'}