# -*- coding: utf-8 -*-
{'name': 'CFON OCR Clean (no IAP)',
 'summary': 'OCR de facturas proveedor (Documentos + plantillas) sin vistas conflictivas',
 'version': '17.0.2.0.0',
 'author': 'CFON',
 'website': 'https://example.com',
 'license': 'LGPL-3',
 'category': 'Accounting/Accounting',
 'depends': ['base', 'account', 'documents'],
 'data': ['security/ir.model.access.csv',
          'views/ocr_template_views.xml',
          'data/documents_rule.xml',
          'data/ocr_templates.xml',
          'data/ocr_templates_extra.xml',
          'data/ocr_templates_last.xml'],
 'assets': {},
 'application': False,
 'installable': True,
 'external_dependencies': {'python': ['pdfminer.six', 'python-dateutil']},
 'description': 'Módulo limpio y seguro: sin xpaths heredados; OCR gratis + plantillas + Documentos.'}