{'name': "Serial Return Alert (Safe v1.3)",
'summary': "Alertas por n.º de serie con 2+ devoluciones. Sin herencias de vista. Compatible con 'stock.production.lot'.",
'version': "17.0.1.3.0",
'category': "Inventory/Logistics",
'author': "CosladaFon (CFON) + ChatGPT",
'license': "LGPL-3",
'website': "https://cosladafon.com",
'depends': ["stock"],
'data': ["views/actions_menus.xml", "security/ir.model.access.csv"],
'installable': true,
'application': false}
