{'name': "Serial Return Report (CFON) v2",
'summary': "Informe seguro de SN/Lotes con 2+ devoluciones y stock interno (sin heredar modelos/vistas).",
'version': "17.0.0.2.0",
'category': "Inventory/Reporting",
'author': "CosladaFon (CFON) + ChatGPT",
'license': "LGPL-3",
'website': "https://cosladafon.com",
'depends': ["stock"],
'data': ["views/report_views.xml", "security/ir.model.access.csv"],
'installable': true,
'application': false}
