# -*- coding: utf-8 -*-
{
    'name': 'Product Purchase History',
    'summary': """You can see purchase history of products in product, variant and puchase order line views""",
    'author': 'Preciseways',
    "category": "purchases",
    'website': "http://www.preciseways.com",
    'version': '17.0',
    "depends": ['purchase'],
    'data': ['security/ir.model.access.csv',
             'views/purchase_view.xml',
             'wizard/product_history_wizard.xml'],
    'application': True,
    'installable': True,
    'price': 15.0,
    'currency': 'EUR',
    'images':['static/description/banner.png'],
    'live_test_url': 'https://preciseways.com',
    'license': 'OPL-1',
}
