{
    'name': 'Hr Employee Extend',
    'version': '18.0',
    'category': 'Human Resources',
    'summary': """ 1 Aug """,
    'description': """ """,
    'author': 'Preciseways',
    'website': 'https://www.preciseways.com',
    'depends': [
                'analytic',
                'hr', 
                'hr_maintenance', 
                'hr_contract',
                'hr_contract_salary',
                'hr_holidays_contract',
            ],
    'data': [
        'security/ir.model.access.csv',
        'data/hr_job_category.xml',
        'data/visa_designation_data.xml',
        'views/account_analytic_view.xml',
        'views/hr_employee.xml',
        'views/hr_job_category.xml',
        'views/hr_visa_designation.xml',
        'views/hr_contract_view.xml',
        'views/hr_hfm_department_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
